<?php
require_once '../includes/config.php';

if (!isLoggedIn() || !isAdmin()) {
    header('Location: ../login.php');
    exit;
}

if (!isset($_GET['id'])) {
    header('Location: orders.php');
    exit;
}

$orderId = (int)$_GET['id'];

// Get order details
$stmt = $pdo->prepare("
    SELECT o.*, u.username, u.full_name, u.email, u.phone, u.address, 
           p.name as product_name, p.description as product_description, p.price, p.image
    FROM orders o
    JOIN users u ON o.user_id = u.id
    JOIN products p ON o.product_id = p.id
    WHERE o.id = ?
");
$stmt->execute([$orderId]);
$order = $stmt->fetch();

if (!$order) {
    header('Location: orders.php');
    exit;
}

// Get payment details (if available)
$stmt = $pdo->prepare("
    SELECT * FROM payments WHERE order_id = ?
");
$executionResult = $stmt->execute([$orderId]);
if (!$executionResult) {
    print_r($stmt->errorInfo()); // This will give you specific error information from the database
    die('Error executing the query.');
}
$payment = $stmt->fetch();

// Get commissions generated by this order
$stmt = $pdo->prepare("
    SELECT c.*, u.full_name as recipient_name, u.username as recipient_username
    FROM commissions c
    JOIN users u ON c.user_id = u.id
    WHERE c.order_id = ?
    ORDER BY c.level
");

$executionResult = $stmt->execute([$orderId]);
if (!$executionResult) {
    print_r($stmt->errorInfo()); // This will give you specific error information from the database
    die('Error executing the query.');
}
$commissions = $stmt->fetchAll();

// Handle status update
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['update_status'])) {
    $newStatus = $_POST['status'];
    $notes = $_POST['notes'];
    
    // Update order status
    $pdo->prepare("UPDATE orders SET payment_status = ?, notes = ? WHERE id = ?")
       ->execute([$newStatus, $notes, $orderId]);
    
    // If changing to completed, process commissions
    if ($newStatus === 'completed' && $order['payment_status'] !== 'completed') {
        getCommissions($orderId);
    }
    
    $_SESSION['success'] = "Order status updated successfully";
    header("Location: order-details.php?id=$orderId");
    exit;
}
?>

<?php include '../includes/header.php'; ?>

<div class="admin-container">
    <div class="row">
        <!-- Admin Sidebar -->
        <?php include 'sidebar.php'; ?>
        
        <!-- Main Content -->
        <div class="col-md-9">
            <?php if (isset($_SESSION['success'])): ?>
                <div class="alert alert-success"><?= $_SESSION['success'] ?></div>
                <?php unset($_SESSION['success']); ?>
            <?php endif; ?>
            
            <div class="card mb-4">
                <div class="card-header bg-primary text-white">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="mb-0">Order #<?= $order['payment_id'] ?></h4>
                        <div>
                            <span class="badge bg-<?= 
                                $order['payment_status'] === 'completed' ? 'success' : 
                                ($order['payment_status'] === 'pending' ? 'warning' : 'danger')
                            ?>">
                                <?= ucfirst($order['payment_status']) ?>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h5>Order Details</h5>
                            <div class="table-responsive">
                                <table class="table table-sm">
                                    <tbody>
                                        <tr>
                                            <th>Order Date:</th>
                                            <td><?= date('M j, Y H:i', strtotime($order['created_at'])) ?></td>
                                        </tr>
                                        <tr>
                                            <th>Payment Status:</th>
                                            <td>
                                                <form method="POST" class="d-inline">
                                                    <div class="input-group input-group-sm">
                                                        <select class="form-select" name="status">
                                                            <option value="pending" <?= $order['payment_status'] === 'pending' ? 'selected' : '' ?>>Pending</option>
                                                            <option value="completed" <?= $order['payment_status'] === 'completed' ? 'selected' : '' ?>>Completed</option>
                                                            <option value="failed" <?= $order['payment_status'] === 'failed' ? 'selected' : '' ?>>Failed</option>
                                                        </select>
                                                        <button type="submit" name="update_status" class="btn btn-primary">
                                                            <i class="fas fa-save"></i>
                                                        </button>
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Payment Method:</th>
                                            <td>Razorpay (Online)</td>
                                        </tr>
                                        <tr>
                                            <th>Payment ID:</th>
                                            <td><?= $order['payment_id'] ?? 'N/A' ?></td>
                                        </tr>
                                        <tr>
                                            <th>Total Amount:</th>
                                            <td>₹<?= number_format($order['total_amount'], 2) ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <h5>Customer Details</h5>
                            <div class="table-responsive">
                                <table class="table table-sm">
                                    <tbody>
                                        <tr>
                                            <th>Name:</th>
                                            <td>
                                                <a href="view-distributor.php?id=<?= $order['user_id'] ?>">
                                                    <?= htmlspecialchars($order['full_name']) ?>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Username:</th>
                                            <td>@<?= $order['username'] ?></td>
                                        </tr>
                                        <tr>
                                            <th>Email:</th>
                                            <td><?= htmlspecialchars($order['email']) ?></td>
                                        </tr>
                                        <tr>
                                            <th>Phone:</th>
                                            <td><?= htmlspecialchars($order['phone']) ?></td>
                                        </tr>
                                        <tr>
                                            <th>Address:</th>
                                            <td><?= nl2br(htmlspecialchars($order['address'])) ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-8">
                            <h5>Order Items</h5>
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex">
                                        <div class="flex-shrink-0">
                                            <img src="../assets/images/product/<?= $order['image'] ?>" alt="<?= htmlspecialchars($order['product_name']) ?>" width="80">
                                        </div>
                                        <div class="flex-grow-1 ms-3">
                                            <h6><?= htmlspecialchars($order['product_name']) ?></h6>
                                            <p class="text-muted small"><?= htmlspecialchars($order['product_description']) ?></p>
                                            <div class="d-flex justify-content-between">
                                                <div>
                                                    <strong>Price:</strong> ₹<?= number_format($order['price'], 2) ?>
                                                </div>
                                                <div>
                                                    <strong>Qty:</strong> <?= $order['quantity'] ?>
                                                </div>
                                                <div>
                                                    <strong>Total:</strong> ₹<?= number_format($order['total_amount'], 2) ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <!-- Commission Breakdown -->
                            <?php if (!empty($commissions)): ?>
                            <h5 class="mt-4">Commission Breakdown</h5>
                            <div class="table-responsive">
                                <table class="table table-sm">
                                    <thead>
                                        <tr>
                                            <th>Level</th>
                                            <th>Recipient</th>
                                            <th>Percentage</th>
                                            <th>Amount</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($commissions as $commission): ?>
                                        <tr>
                                            <td><?= $commission['level'] ?></td>
                                            <td>
                                                <a href="view-distributor.php?id=<?= $commission['user_id'] ?>">
                                                    <?= htmlspecialchars($commission['recipient_name']) ?>
                                                    <small class="text-muted d-block">@<?= $commission['recipient_username'] ?></small>
                                                </a>
                                            </td>
                                            <td><?= $commission['percentage'] ?>%</td>
                                            <td>₹<?= number_format($commission['amount'], 2) ?></td>
                                            <td>
                                                <span class="badge bg-<?= $commission['status'] === 'paid' ? 'success' : 'warning' ?>">
                                                    <?= ucfirst($commission['status']) ?>
                                                </span>
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <?php endif; ?>
                        </div>
                        
                        <div class="col-md-4">
                            <h5>Order Summary</h5>
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between mb-2">
                                        <span>Subtotal:</span>
                                        <span>₹<?= number_format($order['total_amount'] / 1.05, 2) ?></span>
                                    </div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <span>Tax (5%):</span>
                                        <span>₹<?= number_format($order['total_amount'] * 0.05, 2) ?></span>
                                    </div>
                                    <hr>
                                    <div class="d-flex justify-content-between fw-bold">
                                        <span>Total:</span>
                                        <span>₹<?= number_format($order['total_amount'], 2) ?></span>
                                    </div>
                                </div>
                            </div>
                            
                            <!-- Order Notes -->
                            <h5 class="mt-4">Order Notes</h5>
                            <form method="POST">
                                <div class="mb-3">
                                    <textarea class="form-control" name="notes" rows="4"><?= htmlspecialchars($order['notes'] ?? '') ?></textarea>
                                </div>
                                <button type="submit" name="update_status" class="btn btn-primary w-100">
                                    <i class="fas fa-save me-2"></i>Save Notes
                                </button>
                            </form>
                            
                            <!-- Actions -->
                            <div class="mt-4">
                                <button onclick="printInvoice(<?= $order['id'] ?>)" class="btn btn-outline-secondary w-100 mb-2">
                                    <i class="fas fa-print me-2"></i>Print Invoice
                                </button>
                                <a href="orders.php" class="btn btn-outline-primary w-100">
                                    <i class="fas fa-arrow-left me-2"></i>Back to Orders
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function printInvoice(orderId) {
    window.open(`print-invoice.php?id=${orderId}`, '_blank');
}
</script>

<?php include '../includes/footer.php'; ?>